import Link from "next/link";
import "./globals.css";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-amber-600">

        {/* Header */}
        <NavBar />

        {/* Contenu central */}
        <main className="flex-1 w-full p-5">
          {children}
        </main>

        {/* Footer */}
        <Footer />

      </body>
    </html>
  );
}

